---
spring:
  application:
    name: spring-cloud-eureka-double
  profiles: master
server:
  port: 8000
eureka:
  instance:
    hostname: master
  client:
    serviceUrl:
      defaultZone: http://slaves:8001/eureka/
---
spring:
  application:
    name: spring-cloud-eureka-double
  profiles: slaves
server:
  port: 8001
eureka:
  instance:
    hostname: slaves
  client:
    serviceUrl:
      defaultZone: http://master:8000/eureka/
